<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class StocksTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('stocks')->delete();
        
        \DB::table('stocks')->insert(array (
            0 => 
            array (
                'id' => 2,
                'code' => 'BBCA',
                'name' => 'Bank Central Asia Tbk.',
                'sector' => 'Financial Services',
                'sub_sector' => NULL,
                'summary' => 'PT Bank Central Asia Tbk, together with its subsidiaries, provides banking products and services to individual, corporate, and small and medium enterprise customers in Indonesia and internationally',
                'avatar' => 'https://asset.brandfetch.io/idrBYj0urD/idt-Cx7BJO.jpeg',
                'netIncome' => 30294576988160,
                'profitMargin' => 0.45334,
                'operationMargin' => 0.56136,
                'returnOnAsset' => 0.0279,
                'returnOnEquity' => 0.16078,
                'marketCap' => 906071266820096,
                'outstandingShare' => 123275001856,
                'actualPrice' => 7350,
                'created_at' => '2021-12-23',
                'updated_at' => '2021-12-27',
                'created_by' => 1,
            ),
            1 => 
            array (
                'id' => 3,
                'code' => 'BMRI',
            'name' => 'Bank Mandiri (Persero) Tbk.',
                'sector' => 'Financial Services',
                'sub_sector' => NULL,
            'summary' => 'PT Bank Mandiri (Persero) Tbk provides various banking products and services to individuals and businesses in Indonesia, Singapore, Hong Kong, Timor Leste, Shanghai, Malaysia, the United Kingdom, and the Cayman Islands',
                'avatar' => 'https://asset.brandfetch.io/idCtRStnaP/idrE_3ZuBW.jpeg',
                'netIncome' => 22320315891712,
                'profitMargin' => 0.27926,
                'operationMargin' => 0.39799,
                'returnOnAsset' => 0.01594,
                'returnOnEquity' => 0.12068,
                'marketCap' => 326419091554304,
                'outstandingShare' => 46631301120,
                'actualPrice' => 7000,
                'created_at' => '2021-12-23',
                'updated_at' => '2021-12-27',
                'created_by' => 1,
            ),
            2 => 
            array (
                'id' => 4,
                'code' => 'ERAA',
                'name' => 'Erajaya Swasembada Tbk.',
                'sector' => 'Consumer Cyclical',
                'sub_sector' => NULL,
                'summary' => 'PT Erajaya Swasembada Tbk engages in the import, distribution, and retail of mobile telecommunication products in Indonesia. It offers mobile phones and tablets, subscriber identity module cards, prepaid mobile vouchers, accessories, Internet of Things devices, and Google Play gift cards; electric cigarettes; and computers and other electronic devices. The company also provides trades in medical equipment; and provides value added services, including mobile phones protection and handset leasing services. It also engages in information technology system; management consulting; outsourcing; and property businesses. The company was founded in 1996 and is headquartered in West Jakarta, Indonesia. PT Erajaya Swasembada Tbk is a subsidiary of PT Eralink International.',
                'avatar' => 'https://asset.brandfetch.io/idXF8SXagK/iddF04xIDt.jpeg',
                'netIncome' => 1036094210048,
                'profitMargin' => 0.0246,
                'operationMargin' => 0.03906,
                'returnOnAsset' => 0.09832,
                'returnOnEquity' => 0.19735,
                'marketCap' => 9459607797760,
                'outstandingShare' => 15898500096,
                'actualPrice' => 595,
                'created_at' => '2021-12-23',
                'updated_at' => '2021-12-23',
                'created_by' => 1,
            ),
            3 => 
            array (
                'id' => 5,
                'code' => 'TLKM',
            'name' => 'Telkom Indonesia (Persero) Tbk.',
                'sector' => 'Communication Services',
                'sub_sector' => NULL,
            'summary' => 'Perusahaan Perseroan (Persero) PT Telekomunikasi Indonesia Tbk provides telecommunications, informatics, and network services worldwide. The company\'s Mobile segment offers mobile voice, SMS, and mobile broadband services; and digital services, including financial services, video on demand, music, gaming, IoT, big data analytics, and digital advertising services. Its Consumer segment provides fixed voice and broadband services; and IPTV and related consumer digital services. The company\'s Enterprise segment offers ICT and digital platform that covers enterprise-grade connectivity services, including satellite, IT services, data center and cloud, and business process outsourcing services, as well as CPE trading and managed, cyber security, financial, big data, digital advertising, e-health, managed ATM, and professional services. Its Wholesale and International Business segment provides wholesale voice, managed, A2P SMS, IP transit and connectivity, data center and cloud, security, and value added and digital services; mobile network operator, mobile virtual network operator, and call center services; and tower and infrastructure services to other licensed operator companies and institutions. The company\'s Others segment offers digital services, such as digital platform, digital content, and e-commerce; and property management services. The company also provides building management and maintenance services, payment, business management consulting and capital venture, health insurance administration, tourism, directory information, telecommunication construction, and multimedia portal services; acts as a civil consultant and developer; and leases offices. As of December 31, 2020, it had approximately 9.1 million fixed wireline subscribers, including 8.0 million fixed broadband subscribers; and 169.5 million cellular subscribers, including 115.9 million mobile broadband subscribers. The company was founded in 1884 and is headquartered in Bandung, Indonesia.',
                'avatar' => 'https://asset.brandfetch.io/idHTfZR2VA/idYVBf3gfu.png',
                'netIncome' => 22996999733248,
                'profitMargin' => 0.16131,
                'operationMargin' => 0.3284,
                'returnOnAsset' => 0.12199,
                'returnOnEquity' => 0.2727,
                'marketCap' => 412098756608000,
                'outstandingShare' => 99062202368,
                'actualPrice' => 4160,
                'created_at' => '2021-12-23',
                'updated_at' => '2021-12-23',
                'created_by' => 1,
            ),
            4 => 
            array (
                'id' => 6,
                'code' => 'ANTM',
                'name' => 'Aneka Tambang Tbk.',
                'sector' => 'Basic Materials',
                'sub_sector' => NULL,
            'summary' => 'PT Aneka Tambang Tbk operates as a diversified mining and metals company in Indonesia. The company operates through three segments: Nickel, Precious Metals and Refinery, and Bauxite and Alumina. It is involved in the exploration, excavation, processing, and marketing of alumia, nickel ore, ferronickel, gold, silver, bauxite, and coal. The company also engages in the construction, trading, industry, agriculture, printing, and ground transportation businesses; manufacture and sale of stainless steel; and provision of industrial area management and heavy equipment rental services. It also exports its products. The company was incorporated in 1968 and is headquartered in Jakarta, Indonesia. PT Aneka Tambang Tbk is a subsidiary of PT Indonesia Asahan Aluminium (Persero).',
                'avatar' => 'https://asset.brandfetch.io/idazlLDakj/idTsBFczx-.jpeg',
                'netIncome' => 2024029683712,
                'profitMargin' => 0.05652,
                'operationMargin' => 0.09836,
                'returnOnAsset' => 0.06851,
                'returnOnEquity' => 0.10307,
                'marketCap' => 318944640499712,
                'outstandingShare' => 24030799872,
                'actualPrice' => 2240,
                'created_at' => '2021-12-23',
                'updated_at' => '2021-12-23',
                'created_by' => 1,
            ),
            5 => 
            array (
                'id' => 7,
                'code' => 'ASII',
                'name' => 'Astra International Tbk.',
                'sector' => 'Consumer Cyclical',
                'sub_sector' => NULL,
                'summary' => 'PT Astra International Tbk, together with its subsidiaries, operates in the automotive, financial services, heavy equipment, mining, construction, energy, agri, infrastructure and logistics, information technology, and property businesses in Indonesia',
                'avatar' => 'https://asset.brandfetch.io/idXdZiXMOz/idC6LOz6CW.jpeg',
                'netIncome' => 17101999833088,
                'profitMargin' => 0.08063,
                'operationMargin' => 0.1031,
                'returnOnAsset' => 0.03885,
                'returnOnEquity' => 0.10557,
                'marketCap' => 231768598773760,
                'outstandingShare' => 40483598336,
                'actualPrice' => 5725,
                'created_at' => '2021-12-23',
                'updated_at' => '2021-12-28',
                'created_by' => 1,
            ),
            6 => 
            array (
                'id' => 8,
                'code' => 'UNVR',
                'name' => 'Unilever Indonesia Tbk.',
                'sector' => 'Consumer Defensive',
                'sub_sector' => NULL,
                'summary' => 'PT Unilever Indonesia Tbk engages in the manufacture, marketing, and distribution of consumer goods in Indonesia. It offers soaps, detergents, dairy based foods, ice creams, cosmetic products, tea based beverages, and fruit juices. The company provides its products under the Sunlight, Lifebuoy, Walls, Pepsodent, Dove, Royco, Bango, Rexona, Citra, Rinso, Molto, Lux, Superpell, Clear, Sunsilk, TRESemmÃ©, Love Beauty and Planet, Ponds, Sariwangi, Vaseline, Axe, and other brands. It also leases office space. The company was founded in 1933 and is headquartered in Tangerang, Indonesia. PT Unilever Indonesia Tbk is a subsidiary of Unilever Indonesia Holding B.V.',
                'avatar' => 'https://asset.brandfetch.io/idEQ0suOsm/idiWfNh_4U.jpeg',
                'netIncome' => 6589793173504,
                'profitMargin' => 0.15926,
                'operationMargin' => 0.21161,
                'returnOnAsset' => 0.26293,
                'returnOnEquity' => 1.02791,
                'marketCap' => 155651997171712,
                'outstandingShare' => 38150000640,
                'actualPrice' => 4080,
                'created_at' => '2021-12-23',
                'updated_at' => '2021-12-23',
                'created_by' => 1,
            ),
            7 => 
            array (
                'id' => 9,
                'code' => 'ADRO',
                'name' => 'Adaro Energy Tbk.',
                'sector' => 'Energy',
                'sub_sector' => NULL,
                'summary' => 'PT Adaro Energy Tbk, together with its subsidiaries, operates as an integrated coal mining and energy company in Indonesia. It operates through Coal Mining and Trading; Mining Services; Logistics; and Others segments. The company provides coal mining and trading, mining contracting, quarrying, mining support services, warehousing, coal barging and ship loading, channel dredging and maintenance, stevedoring, port services, forestry, power generation, and water and mud treatment services; and coal handling and barging, terminal handling, farming, trading, power plant, and construction services, as well as repair and installation of machines; manufactures, repairs, and maintains sea transportation; and treats mine water into potable water. It also exports its products to China, Malaysia, Japan, India, South Korea, and internationally. The company was formerly known as PT Padang Karunia and changed its name to PT Adaro Energy Tbk in April 2008. PT Adaro Energy Tbk was founded in 2004 and is headquartered in Jakarta, Indonesia.',
                'avatar' => 'https://asset.brandfetch.io/iddW7gwUSs/id83xn2Brw.jpeg',
                'netIncome' => 458451008,
                'profitMargin' => 0.14556,
                'operationMargin' => 0.30753,
                'returnOnAsset' => 0.08909,
                'returnOnEquity' => 0.12252,
                'marketCap' => 68769900658688,
                'outstandingShare' => 31985999872,
                'actualPrice' => 2150,
                'created_at' => '2021-12-23',
                'updated_at' => '2021-12-23',
                'created_by' => 1,
            ),
            8 => 
            array (
                'id' => 10,
                'code' => 'BBRI',
            'name' => 'Bank Rakyat Indonesia (Persero)',
                'sector' => 'Financial Services',
                'sub_sector' => NULL,
            'summary' => 'PT Bank Rakyat Indonesia (Persero) Tbk provides various banking products and services in Indonesia, Singapore, Timor Leste, Hong Kong, and the United States',
                'avatar' => 'https://asset.brandfetch.io/id1zQd_XN4/idtBu4D654.png',
                'netIncome' => 23794909446144,
                'profitMargin' => 0.2976,
                'operationMargin' => 0.29515,
                'returnOnAsset' => 0.01537,
                'returnOnEquity' => 0.09928,
                'marketCap' => 609174606053376,
                'outstandingShare' => 150043000832,
                'actualPrice' => 4060,
                'created_at' => '2021-12-25',
                'updated_at' => '2021-12-27',
                'created_by' => 1,
            ),
            9 => 
            array (
                'id' => 11,
                'code' => 'BBNI',
            'name' => 'Bank Negara Indonesia (Persero)',
                'sector' => 'Financial Services',
                'sub_sector' => NULL,
            'summary' => 'PT Bank Negara Indonesia (Persero) Tbk, together with its subsidiaries, provides banking products and services in Indonesia, the United States, Europe, and Asia',
                'avatar' => 'https://asset.brandfetch.io/idVOhcVfnR/id6ngU71Vc.jpeg',
                'netIncome' => 6707174965248,
                'profitMargin' => 0.2126,
                'operationMargin' => 0.25533,
                'returnOnAsset' => 0.00735,
                'returnOnEquity' => 0.05739,
                'marketCap' => 125579701518336,
                'outstandingShare' => 289342016,
                'actualPrice' => 6750,
                'created_at' => '2021-12-25',
                'updated_at' => '2021-12-27',
                'created_by' => 1,
            ),
            10 => 
            array (
                'id' => 12,
                'code' => 'AGRO',
                'name' => 'Bank Raya Indonesia Tbk.',
                'sector' => 'Financial Services',
                'sub_sector' => NULL,
                'summary' => 'PT Bank Rakyat Indonesia Agroniaga Tbk provides various retail, consumer, and medium commercial banking products and services in Indonesia',
                'avatar' => 'https://asset.brandfetch.io/idE2kxNVyL/idGx4yvIaq.jpeg',
                'netIncome' => -1825968357376,
                'profitMargin' => 0.0,
                'operationMargin' => 1.24329,
                'returnOnAsset' => -0.07534,
                'returnOnEquity' => -0.54209,
                'marketCap' => 44385282555904,
                'outstandingShare' => 22530600960,
                'actualPrice' => 1970,
                'created_at' => '2021-12-25',
                'updated_at' => '2021-12-27',
                'created_by' => 1,
            ),
            11 => 
            array (
                'id' => 13,
                'code' => 'AKRA',
                'name' => 'AKR Corporindo Tbk.',
                'sector' => 'Energy',
                'sub_sector' => NULL,
                'summary' => 'PT AKR Corporindo Tbk, a logistics and supply chain company, distributes and trades in petroleum and basic chemical products primarily in Indonesia',
                'avatar' => 'https://asset.brandfetch.io/idgWNAq6d-/idrz_zVqWH.png',
                'netIncome' => 1056495763456,
                'profitMargin' => 0.05006,
                'operationMargin' => 0.06389,
                'returnOnAsset' => 0.04249,
                'returnOnEquity' => 0.10463,
                'marketCap' => 16263411662848,
                'outstandingShare' => 3947429888,
                'actualPrice' => 4120,
                'created_at' => '2021-12-28',
                'updated_at' => '2021-12-28',
                'created_by' => 1,
            ),
            12 => 
            array (
                'id' => 14,
                'code' => 'BULL',
                'name' => 'Buana Lintas Lautan Tbk.',
                'sector' => 'Industrials',
                'sub_sector' => NULL,
                'summary' => 'PT Buana Lintas Lautan Tbk operates as a shipowner company in Indonesia',
                'avatar' => 'https://asset.brandfetch.io/idhWUW1OeZ/idfBtl3JyG.png',
                'netIncome' => 22198518,
                'profitMargin' => 0.11223,
                'operationMargin' => 0.40807,
                'returnOnAsset' => 0.06506,
                'returnOnEquity' => 0.06745,
                'marketCap' => 3170070167552,
                'outstandingShare' => 13432500224,
                'actualPrice' => 236,
                'created_at' => '2021-12-28',
                'updated_at' => '2021-12-28',
                'created_by' => 1,
            ),
            13 => 
            array (
                'id' => 15,
                'code' => 'ACES',
                'name' => 'Ace Hardware Indonesia Tbk.',
                'sector' => 'Consumer Cyclical',
                'sub_sector' => 'Specialty Retail',
                'summary' => 'PT Ace Hardware Indonesia Tbk engages in the retail of household appliances and lifestyle products in Indonesia',
                'avatar' => 'https://asset.brandfetch.io/idyy9VBGwS/idypkV2Z95.jpeg',
                'netIncome' => 526463434752,
                'profitMargin' => 0.07945,
                'operationMargin' => 0.11212,
                'returnOnAsset' => 0.06694,
                'returnOnEquity' => 0.10794,
                'marketCap' => 21914112229376,
                'outstandingShare' => 17120400384,
                'actualPrice' => 1280,
                'created_at' => '2021-12-28',
                'updated_at' => '2021-12-28',
                'created_by' => 1,
            ),
            14 => 
            array (
                'id' => 16,
                'code' => 'CARE',
                'name' => 'Metro Healthcare Indonesia Tbk.',
                'sector' => 'Healthcare',
                'sub_sector' => 'Medical Care Facilities',
                'summary' => 'PT Metro Healthcare Indonesia Tbk operates and manages hospitals in Indonesia',
                'avatar' => 'https://asset.brandfetch.io/idVGqB9BPO/idl8OBKGkw.png',
                'netIncome' => 21958457344,
                'profitMargin' => 0.07577,
                'operationMargin' => 0.05376,
                'returnOnAsset' => 0.00277,
                'returnOnEquity' => 0.00674,
                'marketCap' => 16625000513536,
                'outstandingShare' => 33250000896,
                'actualPrice' => 500,
                'created_at' => '2021-12-28',
                'updated_at' => '2021-12-28',
                'created_by' => 1,
            ),
            15 => 
            array (
                'id' => 17,
                'code' => 'HEAL',
                'name' => 'Medikaloka Hermina Tbk.',
                'sector' => 'Healthcare',
                'sub_sector' => 'Medical Care Facilities',
                'summary' => 'PT Medikaloka Hermina Tbk operates a network of general hospitals in Indonesia',
                'avatar' => 'http://127.0.0.1:8000/MyLogo.png',
                'netIncome' => 984449024000,
                'profitMargin' => 0.15981,
                'operationMargin' => 0.30898,
                'returnOnAsset' => 0.17884,
                'returnOnEquity' => 0.35737,
                'marketCap' => 14747369996288,
                'outstandingShare' => 14673999872,
                'actualPrice' => 1005,
                'created_at' => '2021-12-28',
                'updated_at' => '2021-12-28',
                'created_by' => 1,
            ),
            16 => 
            array (
                'id' => 18,
                'code' => 'MIKA',
                'name' => 'Mitra Keluarga Karyasehat Tbk.',
                'sector' => 'Healthcare',
                'sub_sector' => 'Medical Care Facilities',
                'summary' => 'PT Mitra Keluarga Karyasehat Tbk, together with its subsidiaries, owns and operates hospitals in Indonesia',
                'avatar' => 'https://asset.brandfetch.io/idjRUbSTwc/idJgBWLVkR.jpeg',
                'netIncome' => 1198995931136,
                'profitMargin' => 0.26585,
                'operationMargin' => 0.36987,
                'returnOnAsset' => 0.16573,
                'returnOnEquity' => 0.2511,
                'marketCap' => 31449631686656,
                'outstandingShare' => 14166500352,
                'actualPrice' => 2220,
                'created_at' => '2021-12-28',
                'updated_at' => '2021-12-28',
                'created_by' => 1,
            ),
            17 => 
            array (
                'id' => 19,
                'code' => 'PRDA',
                'name' => 'Prodia Widyahusada Tbk.',
                'sector' => 'Healthcare',
                'sub_sector' => 'Diagnostics & Research',
                'summary' => 'PT Prodia Widyahusada Tbk provides private clinical laboratory services',
                'avatar' => 'https://asset.brandfetch.io/idTVPWo1WH/idl_CWZghe.jpeg',
                'netIncome' => 657555980288,
                'profitMargin' => 0.24702,
                'operationMargin' => 0.30224,
                'returnOnAsset' => 0.2148,
                'returnOnEquity' => 0.34524,
                'marketCap' => 8156250374144,
                'outstandingShare' => 937500032,
                'actualPrice' => 8700,
                'created_at' => '2021-12-28',
                'updated_at' => '2021-12-28',
                'created_by' => 1,
            ),
            18 => 
            array (
                'id' => 20,
                'code' => 'PRIM',
                'name' => 'Royal Prima Tbk.',
                'sector' => 'Healthcare',
                'sub_sector' => 'Medical Care Facilities',
                'summary' => 'PT Royal Prima Tbk provides hospital services in Indonesia',
                'avatar' => 'http://127.0.0.1:8000/MyLogo.png',
                'netIncome' => 125911736320,
                'profitMargin' => 0.20338,
                'operationMargin' => 0.24608,
                'returnOnAsset' => 0.09152,
                'returnOnEquity' => 0.13545,
                'marketCap' => 1357372063744,
                'outstandingShare' => 3393430016,
                'actualPrice' => 400,
                'created_at' => '2021-12-28',
                'updated_at' => '2021-12-28',
                'created_by' => 1,
            ),
            19 => 
            array (
                'id' => 21,
                'code' => 'SAME',
                'name' => 'Sarana Meditama Metropolitan Tb',
                'sector' => 'Healthcare',
                'sub_sector' => 'Medical Care Facilities',
                'summary' => 'PT Sarana Meditama Metropolitan Tbk engages in the hospital management of OMNI Hospital Pulomas in Pulomas, East Jakarta',
                'avatar' => 'https://asset.brandfetch.io/id7zVqcPZe/idhKoU3yha.png',
                'netIncome' => -303372140544,
                'profitMargin' => -0.41554,
                'operationMargin' => 0.20298,
                'returnOnAsset' => 0.04376,
                'returnOnEquity' => -0.21897,
                'marketCap' => 6235174207488,
                'outstandingShare' => 17129600000,
                'actualPrice' => 364,
                'created_at' => '2021-12-28',
                'updated_at' => '2021-12-28',
                'created_by' => 1,
            ),
            20 => 
            array (
                'id' => 22,
                'code' => 'SILO',
                'name' => 'Siloam International Hospitals',
                'sector' => 'Healthcare',
                'sub_sector' => 'Medical Care Facilities',
                'summary' => 'PT Siloam International Hospitals Tbk, together with its subsidiaries, provides healthcare services in Indonesia',
                'avatar' => 'https://asset.brandfetch.io/idfjO865z4/idQGeXtGm4.jpeg',
                'netIncome' => 696907988992,
                'profitMargin' => 0.07532,
                'operationMargin' => 0.11353,
                'returnOnAsset' => 0.07444,
                'returnOnEquity' => 0.11743,
                'marketCap' => 13289707798528,
                'outstandingShare' => 1615769984,
                'actualPrice' => 8225,
                'created_at' => '2021-12-28',
                'updated_at' => '2021-12-28',
                'created_by' => 1,
            ),
            21 => 
            array (
                'id' => 23,
                'code' => 'SRAJ',
                'name' => 'Sejahteraraya Anugrahjaya Tbk.',
                'sector' => 'Healthcare',
                'sub_sector' => 'Medical Care Facilities',
                'summary' => 'PT Sejahteraraya Anugrahjaya Tbk provides medical services in Indonesia',
                'avatar' => 'http://127.0.0.1:8000/MyLogo.png',
                'netIncome' => 203771445248,
                'profitMargin' => 0.11106,
                'operationMargin' => 0.15631,
                'returnOnAsset' => 0.04151,
                'returnOnEquity' => 0.11219,
                'marketCap' => 3840224002048,
                'outstandingShare' => 12000700416,
                'actualPrice' => 320,
                'created_at' => '2021-12-28',
                'updated_at' => '2021-12-28',
                'created_by' => 1,
            ),
            22 => 
            array (
                'id' => 24,
                'code' => 'BISI',
                'name' => 'BISI International Tbk.',
                'sector' => 'Basic Materials',
                'sub_sector' => 'Agricultural Inputs',
                'summary' => 'PT BISI International Tbk, together with its subsidiaries, engages in the production and sale of hybrid seeds for field crops, horticulture plants, and agri-chemicals in Indonesia',
                'avatar' => 'https://asset.brandfetch.io/idz_Zz-j0T/idEDpMFSl2.png',
                'netIncome' => 348026011648,
                'profitMargin' => 0.17547,
                'operationMargin' => 0.21946,
                'returnOnAsset' => 0.09191,
                'returnOnEquity' => 0.14132,
                'marketCap' => 2984999911424,
                'outstandingShare' => 3000000000,
                'actualPrice' => 995,
                'created_at' => '2021-12-28',
                'updated_at' => '2021-12-28',
                'created_by' => 1,
            ),
            23 => 
            array (
                'id' => 25,
                'code' => 'AALI',
                'name' => 'Astra Agro Lestari Tbk.',
                'sector' => 'Consumer Defensive',
                'sub_sector' => 'Farm Products',
                'summary' => 'PT Astra Agro Lestari Tbk, together with its subsidiaries, engages in the palm oil business',
                'avatar' => 'https://asset.brandfetch.io/idky9r11Do/idxOOVTN44.png',
                'netIncome' => 1719727947776,
                'profitMargin' => 0.07319,
                'operationMargin' => 0.12451,
                'returnOnAsset' => 0.06326,
                'returnOnEquity' => 0.09102,
                'marketCap' => 18477024804864,
                'outstandingShare' => 1924690048,
                'actualPrice' => 9600,
                'created_at' => '2021-12-28',
                'updated_at' => '2021-12-28',
                'created_by' => 1,
            ),
            24 => 
            array (
                'id' => 26,
                'code' => 'ANDI',
                'name' => 'Andira Agro Tbk.',
                'sector' => 'Consumer Defensive',
                'sub_sector' => 'Farm Products',
                'summary' => 'PT Andira Agro Tbk owns, operates, and manages a crude palm oil mill and oil plantations in Indonesia',
                'avatar' => 'https://asset.brandfetch.io/idHNiDQAV6/idXuAG6JlD.png',
                'netIncome' => -31136948224,
                'profitMargin' => -0.09362,
                'operationMargin' => -0.06522,
                'returnOnAsset' => -0.02723,
                'returnOnEquity' => -0.11564,
                'marketCap' => 467499974656,
                'outstandingShare' => 9349999616,
                'actualPrice' => 50,
                'created_at' => '2021-12-28',
                'updated_at' => '2021-12-28',
                'created_by' => 1,
            ),
            25 => 
            array (
                'id' => 27,
                'code' => 'CSRA',
                'name' => 'Cisadane Sawit Raya Tbk.',
                'sector' => 'Consumer Defensive',
                'sub_sector' => 'Farm Products',
                'summary' => 'PT Cisadane Sawit Raya Tbk',
                'avatar' => 'https://asset.brandfetch.io/idqvXwnWBL/idO353rKfd.jpeg',
                'netIncome' => 187085144064,
                'profitMargin' => 0.23124,
                'operationMargin' => 0.39119,
                'returnOnAsset' => 0.13063,
                'returnOnEquity' => 0.28108,
                'marketCap' => 1076250017792,
                'outstandingShare' => 2050000000,
                'actualPrice' => 525,
                'created_at' => '2021-12-28',
                'updated_at' => '2021-12-28',
                'created_by' => 1,
            ),
            26 => 
            array (
                'id' => 28,
                'code' => 'DSNG',
                'name' => 'Dharma Satya Nusantara Tbk.',
                'sector' => 'Consumer Defensive',
                'sub_sector' => 'Farm Products',
                'summary' => 'PT Dharma Satya Nusantara Tbk engages in palm oil and wood product business in Indonesia',
                'avatar' => 'https://asset.brandfetch.io/idBGtDzkkC/id49tpu2FD.png',
                'netIncome' => 728747016192,
                'profitMargin' => 0.09887,
                'operationMargin' => 0.18613,
                'returnOnAsset' => 0.06688,
                'returnOnEquity' => 0.1429,
                'marketCap' => 4813559955456,
                'outstandingShare' => 9627119616,
                'actualPrice' => 500,
                'created_at' => '2021-12-28',
                'updated_at' => '2021-12-28',
                'created_by' => 1,
            ),
        ));
        
        
    }
}